# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1368, 768)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1368, 768))
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1371, 771))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.NameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.NameLabel.setFont(font)
        self.NameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NameLabel.setObjectName("NameLabel")
        self.gridLayout.addWidget(self.NameLabel, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(70, 50, 1221, 671))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.templateView = QtWidgets.QListView(self.gridLayoutWidget_2)
        self.templateView.setViewMode(QtWidgets.QListView.IconMode)
        self.templateView.setObjectName("templateView")
        self.gridLayout_2.addWidget(self.templateView, 1, 0, 1, 1)
        self.templateSelectLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(27)
        self.templateSelectLabel.setFont(font)
        self.templateSelectLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.templateSelectLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.templateSelectLabel.setObjectName("templateSelectLabel")
        self.gridLayout_2.addWidget(self.templateSelectLabel, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 1311, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.CancelButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CancelButton.sizePolicy().hasHeightForWidth())
        self.CancelButton.setSizePolicy(sizePolicy)
        self.CancelButton.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CancelButton.setFont(font)
        self.CancelButton.setObjectName("CancelButton")
        self.gridLayout_3.addWidget(self.CancelButton, 2, 1, 1, 1)
        self.SaveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveButton.sizePolicy().hasHeightForWidth())
        self.SaveButton.setSizePolicy(sizePolicy)
        self.SaveButton.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.gridLayout_3.addWidget(self.SaveButton, 2, 0, 1, 1)
        self.resultTextLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.resultTextLabel.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.resultTextLabel.setFont(font)
        self.resultTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultTextLabel.setObjectName("resultTextLabel")
        self.gridLayout_3.addWidget(self.resultTextLabel, 0, 0, 1, 2)
        self.resultImageLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.resultImageLabel.sizePolicy().hasHeightForWidth())
        self.resultImageLabel.setSizePolicy(sizePolicy)
        self.resultImageLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.resultImageLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.resultImageLabel.setObjectName("resultImageLabel")
        self.gridLayout_3.addWidget(self.resultImageLabel, 1, 0, 1, 2)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.NameLabel_2 = QtWidgets.QLabel(self.page_5)
        self.NameLabel_2.setGeometry(QtCore.QRect(0, 0, 1369, 769))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.NameLabel_2.setFont(font)
        self.NameLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.NameLabel_2.setObjectName("NameLabel_2")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.NameLabel_3 = QtWidgets.QLabel(self.page_6)
        self.NameLabel_3.setGeometry(QtCore.QRect(0, 0, 1369, 769))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.NameLabel_3.setFont(font)
        self.NameLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.NameLabel_3.setObjectName("NameLabel_3")
        self.stackedWidget.addWidget(self.page_6)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NameLabel.setText(_translate("MainWindow", "Qt-Py PhotoBooth"))
        self.templateSelectLabel.setText(_translate("MainWindow", "Please Select a Template"))
        self.CancelButton.setText(_translate("MainWindow", "Cancel"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.resultTextLabel.setText(_translate("MainWindow", "Your Photo is Ready!"))
        self.resultImageLabel.setText(_translate("MainWindow", "TextLabel"))
        self.NameLabel_2.setText(_translate("MainWindow", "Saving Photo..."))
        self.NameLabel_3.setText(_translate("MainWindow", "Photo Saved Successfully!"))

